# Area for small tests and snippets

## CSV

In [13]:
import numpy as np
a = np.array([5.45, -0.54, 1.81, 1.49, 0.48, 3.98, 0.93, 3.98])
np.savetxt("foo.csv", a, delimiter=",")

In [14]:
! cat foo.csv

5.450000000000000178e+00
-5.400000000000000355e-01
1.810000000000000053e+00
1.489999999999999991e+00
4.799999999999999822e-01
3.979999999999999982e+00
9.300000000000000488e-01
3.979999999999999982e+00


In [1]:
%reload_ext fortranmagic

In [23]:
%%fortran
subroutine dataread(F, N, A)
    character(*), intent(in) :: F
    integer, intent(in) :: N
    real(kind=8), dimension(N), intent(out) :: A
    open(unit=1, file=F, status='old' ,action='read')
    read(1, *) A
    close(unit=1)
end

In [25]:
dataread('foo.csv', 8)

array([ 5.45, -0.54,  1.81,  1.49,  0.48,  3.98,  0.93,  3.98])

In [22]:
import numpy as np
np.savetxt("data.csv", np.random.rand(8))

In [26]:
dataread('data.csv', 8)

array([0.39883258, 0.42250985, 0.4302079 , 0.84548039, 0.23139905,
       0.53823888, 0.99016392, 0.37303136])

### Shape

In [37]:
%%fortran
subroutine main(A, B, C, D)
    integer, dimension(3), intent(out) :: A
    integer, intent(out) :: B, C, D
    real, dimension(3,2,1) :: G
    A = shape(G)
    B = size(G,1)
    C = size(G,2)
    D = size(G,3)
end

In [38]:
main()

(array([3, 2, 1], dtype=int32), 3, 2, 1)

## Random seed

In [3]:
%reload_ext fortranmagic

In [8]:
%%fortran
subroutine main(A)
    real(8), intent(out) :: A(3,3,3)
    call random_seed(put=[0, 0, 0, 0, 0, 0, 0, 0])
    call random_number(A)
end

In [9]:
main()

array([[[0.4710776 , 0.48932975, 0.60925987],
        [0.18629752, 0.89838004, 0.00678346],
        [0.2547749 , 0.42016636, 0.2152564 ]],

       [[0.11734613, 0.71834291, 0.38438552],
        [0.27928683, 0.6086828 , 0.90286098],
        [0.95014959, 0.03347037, 0.14902492]],

       [[0.88488368, 0.30022668, 0.21738487],
        [0.41498327, 0.91296189, 0.66618389],
        [0.5068759 , 0.81491469, 0.58335117]]])

In [10]:
main()

array([[[0.4710776 , 0.48932975, 0.60925987],
        [0.18629752, 0.89838004, 0.00678346],
        [0.2547749 , 0.42016636, 0.2152564 ]],

       [[0.11734613, 0.71834291, 0.38438552],
        [0.27928683, 0.6086828 , 0.90286098],
        [0.95014959, 0.03347037, 0.14902492]],

       [[0.88488368, 0.30022668, 0.21738487],
        [0.41498327, 0.91296189, 0.66618389],
        [0.5068759 , 0.81491469, 0.58335117]]])

### lowercase and uppercase

In [11]:
a = 1
A = 2
print(a, A)

1 2


### "for" within the attribution

In [12]:
n = 3
a = [[1.0 / (i - j + 0.5) for i in range(n)] for j in range(n)]
a

[[2.0, 0.6666666666666666, 0.4],
 [-2.0, 2.0, 0.6666666666666666],
 [-0.6666666666666666, -2.0, 2.0]]

In [14]:
import numpy as np
a = np.array(a)
a

array([[ 2.        ,  0.66666667,  0.4       ],
       [-2.        ,  2.        ,  0.66666667],
       [-0.66666667, -2.        ,  2.        ]])