# Area for small tests and snippets

## CSV

In [13]:
import numpy as np
a = np.array([5.45, -0.54, 1.81, 1.49, 0.48, 3.98, 0.93, 3.98])
np.savetxt("foo.csv", a, delimiter=",")

In [14]:
! cat foo.csv

5.450000000000000178e+00
-5.400000000000000355e-01
1.810000000000000053e+00
1.489999999999999991e+00
4.799999999999999822e-01
3.979999999999999982e+00
9.300000000000000488e-01
3.979999999999999982e+00


In [1]:
%reload_ext fortranmagic

In [23]:
%%fortran
subroutine dataread(F, N, A)
    character(*), intent(in) :: F
    integer, intent(in) :: N
    real(kind=8), dimension(N), intent(out) :: A
    open(unit=1, file=F, status='old' ,action='read')
    read(1, *) A
    close(unit=1)
end

In [25]:
dataread('foo.csv', 8)

array([ 5.45, -0.54,  1.81,  1.49,  0.48,  3.98,  0.93,  3.98])

In [22]:
import numpy as np
np.savetxt("data.csv", np.random.rand(8))

In [26]:
dataread('data.csv', 8)

array([0.39883258, 0.42250985, 0.4302079 , 0.84548039, 0.23139905,
       0.53823888, 0.99016392, 0.37303136])

### Shape

In [37]:
%%fortran
subroutine main(A, B, C, D)
    integer, dimension(3), intent(out) :: A
    integer, intent(out) :: B, C, D
    real, dimension(3,2,1) :: G
    A = shape(G)
    B = size(G,1)
    C = size(G,2)
    D = size(G,3)
end

In [38]:
main()

(array([3, 2, 1], dtype=int32), 3, 2, 1)

## Random seed

In [3]:
%reload_ext fortranmagic

In [8]:
%%fortran
subroutine main(A)
    real(8), intent(out) :: A(3,3,3)
    call random_seed(put=[0, 0, 0, 0, 0, 0, 0, 0])
    call random_number(A)
end

In [9]:
main()

array([[[0.4710776 , 0.48932975, 0.60925987],
        [0.18629752, 0.89838004, 0.00678346],
        [0.2547749 , 0.42016636, 0.2152564 ]],

       [[0.11734613, 0.71834291, 0.38438552],
        [0.27928683, 0.6086828 , 0.90286098],
        [0.95014959, 0.03347037, 0.14902492]],

       [[0.88488368, 0.30022668, 0.21738487],
        [0.41498327, 0.91296189, 0.66618389],
        [0.5068759 , 0.81491469, 0.58335117]]])

In [10]:
main()

array([[[0.4710776 , 0.48932975, 0.60925987],
        [0.18629752, 0.89838004, 0.00678346],
        [0.2547749 , 0.42016636, 0.2152564 ]],

       [[0.11734613, 0.71834291, 0.38438552],
        [0.27928683, 0.6086828 , 0.90286098],
        [0.95014959, 0.03347037, 0.14902492]],

       [[0.88488368, 0.30022668, 0.21738487],
        [0.41498327, 0.91296189, 0.66618389],
        [0.5068759 , 0.81491469, 0.58335117]]])

### lowercase and uppercase

In [11]:
a = 1
A = 2
print(a, A)

1 2


### "for" within the attribution

In [12]:
n = 3
a = [[1.0 / (i - j + 0.5) for i in range(n)] for j in range(n)]
a

[[2.0, 0.6666666666666666, 0.4],
 [-2.0, 2.0, 0.6666666666666666],
 [-0.6666666666666666, -2.0, 2.0]]

In [14]:
import numpy as np
a = np.array(a)
a

array([[ 2.        ,  0.66666667,  0.4       ],
       [-2.        ,  2.        ,  0.66666667],
       [-0.66666667, -2.        ,  2.        ]])

## Structured arrays
- https://docs.scipy.org/doc/numpy-1.13.0/user/basics.rec.html

In [23]:
import numpy as np
x = np.array([(1,2.,'Hello'), (2,3.,"World")],
             dtype=[('foo', 'i4'),('bar', 'f8'), ('baz', 'S10')])
x

array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('foo', '<i4'), ('bar', '<f8'), ('baz', 'S10')])

In [24]:
y = x['bar']
y

array([2., 3.])

In [25]:
y[:] = 2 * y    # the ':' is important
y

array([4., 6.])

In [26]:
x    # 'x' changed. 'y' worked as a pointer

array([(1, 4., b'Hello'), (2, 6., b'World')],
      dtype=[('foo', '<i4'), ('bar', '<f8'), ('baz', 'S10')])

## Numpy array pointer-like

In [36]:
a = np.array([1])
a

array([1])

In [37]:
a = a + 1
a

array([2])

In [38]:
b = a
b

array([2])

In [39]:
id(a) == id(b)

True

In [42]:
b[:] = 3
b

array([3])

In [43]:
a    # 'a' changed

array([3])

## List pointer-like

In [51]:
c = [1]
c

[1]

In [54]:
d = c
d[0] = 100

In [55]:
c

[100]

In [56]:
type(d)

list

## Dictionary pointer-like

In [71]:
e = {'number' : 1}
f = e
f

{'number': 1}

In [73]:
f['number'] = 2
e

{'number': 2}

## tofile / fromfile (binary)

In [20]:
import numpy as np       # create
a = (np.random.rand(2,2,2) + 1j * np.random.rand(2,2,2)).astype(np.complex128)

In [21]:
a    # show

array([[[0.46642205+0.14711512j, 0.8763719 +0.6163763j ],
        [0.90368572+0.00745909j, 0.37919194+0.12722942j]],

       [[0.50793953+0.15368705j, 0.1467613 +0.79373778j],
        [0.70694642+0.223432j  , 0.04254138+0.08338178j]]])

In [23]:
a.dtype

dtype('complex128')

In [24]:
a.shape

(2, 2, 2)

In [25]:
a.tofile('test.bin')  # save as binary

In [26]:
! ls -lh test.bin

-rw-rw-r-- 1 x x 128 jan 31 17:46 test.bin


### Load file

In [27]:
b = np.fromfile('test.bin', dtype=np.complex128).reshape((2,2,2))

In [28]:
b    # show

array([[[0.46642205+0.14711512j, 0.8763719 +0.6163763j ],
        [0.90368572+0.00745909j, 0.37919194+0.12722942j]],

       [[0.50793953+0.15368705j, 0.1467613 +0.79373778j],
        [0.70694642+0.223432j  , 0.04254138+0.08338178j]]])